# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_2R-uqg6Cy1lplM27ziQbBSOIhC7TKV
"""

import sqlite3
import pandas as pd
import os
import json
import time
from google import genai
from google.colab import userdata


try:
    GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
    genai_client = genai.Client(api_key=GOOGLE_API_KEY)
    print("API Key loaded.")
except Exception as e:
    print(f"Error loading API Key: {e}")

DB_NAME = 'wholesale.db'

def setup_database():
    required_files = ['clients.sql', 'catalog.sql', 'invoices.sql']
    missing_files = [f for f in required_files if not os.path.exists(f)]

    if missing_files:
        print(f"STOP! Missing files: {missing_files}")
        return False

    if os.path.exists(DB_NAME):
        try:
            os.remove(DB_NAME)
            print(f" Old database removed.")
        except PermissionError:
            print(" Could not delete old DB. Proceeding...")

    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute("PRAGMA foreign_keys = ON;")

    print(" Building Database...")
    try:
        for filename in required_files:
            with open(filename, 'r') as f:
                cursor.executescript(f.read())
                print(f"   -> Executed {filename}")

        conn.commit()
        print(" Database built successfully!")
        return True
    except Exception as e:
        print(f" Database Build Error: {e}")
        return False
    finally:
        conn.close()

if not setup_database():
    exit()

prompt = """
### ROLE
You are an expert SQLite Database Engineer.

### CONTEXT
You are querying a Wholesale Database with these tables:
1. `clients` (client_id, company_name, region)
2. `catalog` (product_id, product_name, category, cost_price, unit_price)
3. `invoices` (invoice_id, client_id, product_id, quantity)

### RULES
- **Revenue** = SUM(invoices.quantity * catalog.unit_price)
- **Profit** = SUM((catalog.unit_price - catalog.cost_price) * invoices.quantity)
- Join tables using `client_id` and `product_id`.
- Return ONLY the raw SQL.
"""

def get_sql_query(client, prompt, user_query):
    contents = f"{prompt}\n\nQuery: {user_query}"
    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=contents
        )
        text = response.text

        text = text.replace('```sql', '').replace('```', '')

        if "SELECT" in text.upper():
            start_idx = text.upper().find("SELECT")
            text = text[start_idx:]

        return text.strip()

    except Exception as e:
        return f"Error: {e}"

def execute_query(query):
    conn = sqlite3.connect(DB_NAME)
    try:
        df = pd.read_sql_query(query, conn)
        return df
    except Exception as e:
        return f"SQL Error: {e}"
    finally:
        conn.close()

def text2sql(client, prompt, user_query):
    print(f"\n Asking: '{user_query}'")

    sql = get_sql_query(client, prompt, user_query)

    if "429" in sql:
        print(" Rate Limit Hit. Waiting 10 seconds...")
        time.sleep(10)
        sql = get_sql_query(client, prompt, user_query)

    if "SELECT" in sql.upper():
        print(f" SQL: {sql}")
        result = execute_query(sql)
        if isinstance(result, pd.DataFrame):
            print("\n Result:")
            print(result.head().to_string(index=False))
        else:
            print(f" Execution Error: {result}")
    else:
        print(f" AI Error: {sql}")

    print("Processing...")
    time.sleep(5)

text2sql(genai_client, prompt, "Show me the first 3 clients.")
text2sql(genai_client, prompt, "What are the top 3 most profitable products?")
text2sql(genai_client, prompt, "What is the total revenue by region?")

