# -*- coding: utf-8 -*-
"""TEXT2SQL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aJN4fihNNKPPia6Pxd9wkQFktwMLL5vq
"""

import streamlit as st
import sqlite3
import pandas as pd
import google.generativeai as genai
import altair as alt
import os
import time

API_KEY = "YOUR_API_KEY"
DB_NAME = "wholesale.db"

try:
    genai.configure(api_key=API_KEY)
except Exception as e:
    st.error(f"API Key Error: {e}")

SYSTEM_PROMPT = """
You are an expert Data Analyst.
Your job is to convert English business questions into executable SQLite queries for the `wholesale.db` database.

### SCHEMA
1. **clients** (client_id, company_name, region, contact_name, contact_email)
2. **catalog** (product_id, product_name, category, cost_price, unit_price)
3. **invoices** (invoice_id, client_id, product_id, invoice_date, quantity)

### RELATIONSHIPS
- `invoices.client_id` links to `clients.client_id`
- `invoices.product_id` links to `catalog.product_id`

### METRIC LOGIC
- **Revenue** = SUM(invoices.quantity * catalog.unit_price)
- **Profit** = SUM(invoices.quantity * (catalog.unit_price - catalog.cost_price))
- **Margin** = (Profit / Revenue) * 100
- If asked for "Sales", assume "Revenue".

### RULES
- Return ONLY the raw SQL query. No Markdown (```sql). No explanations.
- Always use JOINs when the question involves names (Company, Product).
- Date format is YYYY-MM-DD.
"""

def get_sql_from_ai(user_question):
    try:
        model = genai.GenerativeModel('gemini-2.5-flash')
        response = model.generate_content(f"{SYSTEM_PROMPT}\n\nUser Question: {user_question}")
        sql = response.text.replace('```sql', '').replace('```', '').replace('ite', '').strip()
        if "SELECT" in sql.upper():
            return sql[sql.upper().find("SELECT"):]
        return sql
    except Exception as e:
        st.error(f"AI Error: {e}")
        return None

def run_query(sql_query):
    try:
        conn = sqlite3.connect(DB_NAME)
        df = pd.read_sql_query(sql_query, conn)
        conn.close()
        return df
    except Exception as e:
        return f"SQL Error: {e}"

st.set_page_config(page_title="TEXT2SQL", page_icon="📊", layout="wide")

with st.sidebar:
    st.title("🔧 Data Control")
    if os.path.exists(DB_NAME):
        st.success("Database Connected")
        with st.expander("View Database Schema", expanded=True):
            st.markdown("""
            **📂 Table: CLIENTS**
            - *client_id*, *company_name*, *region*

            **📂 Table: CATALOG**
            - *product_id*, *product_name*, *category*, *cost_price*, *unit_price*

            **📂 Table: INVOICES**
            - *invoice_id*, *client_id*, *product_id*, *quantity*, *date*
            """)
    else:
        st.error("Database Missing!")


st.title("Text2SQL Studio")

col1, col2, col3 = st.columns(3)
query = ""
if col1.button("💰 Top Profit Products", use_container_width=True):
    query = "List the top 5 products by total profit."
if col2.button("🌍 Revenue by Region", use_container_width=True):
    query = "Show total revenue grouped by region."
if col3.button("🏆 Best Customers", use_container_width=True):
    query = "Who are the top 5 clients by sales volume?"


user_input = st.text_input("Or type your question:", value=query)

if user_input:
    with st.spinner("Analyzing Data..."):
        sql_query = get_sql_from_ai(user_input)
        with st.expander("View Generated SQL"):
            st.code(sql_query, language="sql")

        if sql_query:
            results = run_query(sql_query)
            if isinstance(results, pd.DataFrame):
                if not results.empty:
                    st.success("Analysis Complete")
                    st.dataframe(results, use_container_width=True)


                    numeric_cols = results.select_dtypes(include=['number']).columns
                    if len(numeric_cols) > 0 and len(results) > 1:
                        x_col = results.columns.difference(numeric_cols)[0]
                        y_col = numeric_cols[0]

                        if "region" in x_col.lower() or "category" in x_col.lower() or "industry" in x_col.lower():
                            chart = alt.Chart(results).mark_arc(innerRadius=50).encode(
                                theta=alt.Theta(field=y_col, type="quantitative"),
                                color=alt.Color(field=x_col, type="nominal"),
                                tooltip=[x_col, y_col]
                            ).properties(title=f"{y_col} Distribution by {x_col}")

                            st.altair_chart(chart, use_container_width=True)

                        else:
                            chart = alt.Chart(results).mark_bar().encode(
                                x=alt.X(x_col, sort=None, axis=alt.Axis(labelAngle=0, title=x_col)),
                                y=alt.Y(y_col, title=y_col),
                                tooltip=[x_col, y_col],
                                color=alt.Color(x_col, legend=None)
                            ).properties(
                                title=f"{y_col} by {x_col}"
                            ).interactive()

                            st.altair_chart(chart, use_container_width=True)
                else:
                    st.warning("No data found.")
            else:
                st.error(results)